name: validicitytool
description: The CLI tool for managing Validicity
version: 0.1.0
author: Göran Krampe <goran.krampe@gmail.com>

environment:
  sdk: '>=2.7.1'

executables:  
  validicitytool: validicitytool

dependencies:
  async: ^2.4.1
  args: ^1.5.2
  http: ^0.12.1
  logging: ^0.11.3+2

  validicitylib:
    path: ../validicitylib

